#+TITLE: Transitividad
#+author: Emilio Junoy
#+DATE: [2025-08-28]
#+EXPORT_FILE_NAME: transitividad
#+STARTUP: overview

* Álgebras de Heyting
Un álgebra de Heyting es una retícula (pre-orden con todos los "meets" y "joins" finitos,
es decir, máximas cotas inferiores y mínimas cotas superiores) que tiene exponenciales.

En un álgebra de Heyting podemos definir la negación de \(A\) como
\[ \lnot A := A \supset \bot = \bot^A \]
Es decir, la \(C\) más grande que es inconsistente con \(A\).

** Observaciones
- Toda álgebra de Heyting es distributiva.
- Toda álgebra Booleana tiene exponenciales
        \[
                B^A := \lnot A \lor B
        \]

* Álgebras Booleana
Un álgebra Booleana es una retícula complementada (\(\overline{A}\) es la \(C\) más pequeña
tal que \(A \lor C \geq \top\)) y distributiva.

** Afirmación
@@html:<em>@@ En la lógica intuicionista no todas las instancias del tercio excluso son
demostrables @@html:</em>@@ @@html:<br>@@
En general, no podemos esperar que para cada \( A \) que \( A \lor \lnot A ~ True \).

*** Idea (Propiedad de la disyunción) @@html:</b>@@ @@html:<br>@@
Si podemos mostrar que \( A \lor B ~ True\) entonces podemos mostrar \(A ~ True\) o
\(B ~ True\).

** Afirmación (Continuación)
Por lo tanto, si eso fuera cierto, para cada \(A\) tendríamos \(A ~ True\) o
\(A ~ False\), lo cual es refutable. Basta pensar en un problema abierto de la matemática.


* IPL (Lógica Proposicional Intuicionista) desde la teoría de la demostración
*** Afirmación
En la lógica proposicional intuicionista, no todas las instancias de la ley del tercio excluso son
demostrables, es decir, no es cierto que para cada \(A\), \(A \lor \lnot A ~ True\).

La idea de porqué esto no es cierto es la propiedad de la disyunción, que dice que si
queremos mostrar que \(A \lor B ~ True\) entonces debemos probar que \(A~ True\) o \(B ~ True\).
Aplicando esta idea a nuestro caso, vemos que para mostrar \(A \lor \lnot A ~ True\) deberíamos de ser capaces de
dar una prueba o una refutación de \(A\), lo cual no siempre sucede, basta pensar en algún problema abierto.

*** Definición
\(A ~ Prop\) es decidible si \(A \lor \lnot A ~ True\)
**** Ejemplos
- Si \(A = \top\), entonces \(A\) es decidible.
- Si \(A = \bot\), entonces \(A\) es decidible.

*** Definición
\(A ~ Prop\) es estable si y sólo si \(\lnot(\lnot A) \supset \top ~ True\)

*** Afirmación
Para cada \(A\), \(\lnot (\lnot (A \lor \lnot A))\), es decir, la ley del tercio excluso no es refutable.
**** Demostración
Supongamos, en busca de una contradicción, que \(\lnot(A\lor\lnot A)\).
Es suficiente probar \(A \lor \lnot A\) y, para esto, es suficiente que probemos \(\lnot A\).
Para probar esto, supongamos \(A\), entonces \(A \lor \lnot A\), lo cual es una contradicción que lo que habíamos
supuesto.

*** Corolario
No toda proposición es estable.



** ¿Cómo probamos la propiedad de la disyunción en IPL?
Interpretamos las reglas que habíamos dado de IPL como una definición inductiva de la implicación lógica.
*** Teorema
Si \( \emptyset \vdash A \lor B ~ True\), entonces \(\emptyset \vdash A ~ True\) o \(\emptyset \vdash B ~ True\).

* La idea de Gentzen (principio de inversión)
~elim~ es post-inverso a ~intro~.
