#+title: Teoría de tipos dependientes
#+author: mou
#+date: <2025-09-20 Sat>
#+export_file_name: dependiente
#+startup: overview

La teoría de tipos dependiente es un sistema de reglas que se puede combinar para crear *derivaciones*. En
estas derivaciones, la meta es frecuentemente construir un elemento de un cierto tipo. Un elemento así puede
ser una función si el tipo del elemento a construir es un tipo función, una demostración de una propiedad
si el tipo del elemento a construir es una proposición, pero también puede ser una identificación si el tipo
del elemento a construir es un tipo identidad, etc. En cierto respecto, un tipo es sólo una colección de
objetos matemáticos y la construcción de elementos de un cierto tipo es la tarea o desafío matemático del
día a día. El sistema de reglas de inferencia al que llamamos teoría de tipos nos da una forma de
participar en esta actividad.

* Juicios y contextos en la teoría de tipos
Un argumento matemático o construcción cosiste de una secuencia de pasos deductivos, cada uno con una
cantidad finita de premisas para llegar a la siguiente etapa de la demostración o construcción. Estos
pasos se pueden representar mediante *reglas de inferencia*, que se escriben de la siguiente forma:
\[
        \frac{\mathcal{H}_1 ~~~ \mathcal{H}_2 ~~~ \ldots ~~~ \mathcal{H}_n}{\mathcal{C}}.
\]
Las reglas de inferencia contienen, arriba de la línea horizontal, una lista finita \(\mathcal{H}_1,
\mathcal{H}_2, \ldots, \mathcal{H}_n\)
de juicios como las *premisas* y, debajo de la misa línea, un único juicio \(\mathcal{C}\) como la *conclusión*. El sistema
de la teoría de tipos dependiente es un conjunto de este tipo de reglas de inferencia.

Un ejemplo directo de una regla de inferencia con la que nos vamos a encontrar cuando introduzcamos los tipos
función, es la regla de inferencia
\[
        \frac{\Gamma \vdash a: A ~~~ \Gamma \vdash f: A \to B}{\Gamma \vdash f(a): B}.
\]
Esta regla asegura que bajo cualquier contexto \(\Gamma\) podemos usar un elemento \(a: A\) y una función
\(f: A \to B\) para obtener un elemento \(f(a): B\). Cada una de las expresiones
- \(\Gamma \vdash a: A\)
- \(\Gamma \vdash f: A \to B\)
- \(\Gamma \vdash f(a): B\)
son ejemplos de juicios.

** Definición 1.1.1
:PROPERTIES:
:CUSTOM_ID: definicion-1-1-1
:END:
Hay cuatro tipos de *juicios* en la teoría de tipos dependiente de Martin-Löf:
1. \(A\) es un *tipo* (bien formado) en el contexto \(\Gamma\). Expresamos este juicio como \[ \Gamma \vdash A ~~~ \text{type} \].
2. \(A\) y \(B\) son *tipos juiciosamente iguales* en el contexto \(\Gamma\). Expresamos este juicio como
   \[ \Gamma \vdash A \stackrel{\cdot}{=} B ~~~ \text{type}\].
3. \(a\) es un *elemento* de tipo \(A\) en el contexto \(\Gamma\). Expresamos este juicio como
   \[ \Gamma \vdash a: A \].
4.  \(a\) y \(b\) son *elementos juiciosamente iguales* del tipo \(A\) en el contexto \(\Gamma\). Expresamos este
   juicio como \[ \Gamma \vdash a \stackrel{\cdot}{=} b: A \].

Vemos que todos los juicios son de la forma \(\Gamma \vdash \mathcal{J}\), consistiendo de un contexto \(\Gamma\)
y una tesis de juicio \(\mathcal{J}\) que asegura ya sea que \(A\) es un tipo, que \(A\) y \(B\) son tipos
iguales, que \(a\) es un elemento del tipo \(A\) o que \(a\) y \(b\) son elementos iguales del mismo tipo
\(A\). El rol del contexto es declara qué *elementos hipotéticos* son asumidos, junto con sus tipos.
Los elementos hipotéticos son comúnmente llamados *variables*.

** Definición 1.1.2
:PROPERTIES:
:CUSTOM_ID: definicion-1-1-2
:END:
Un *contexto* es una lista finita de *declaraciones de variables*
\[\tag{1.1.1}\label{eq:lista-contexto}
  x_1: A_1, x_2: A_2(x_1), \ldots, x_n: A_n(x_1, \ldots, x_{n-1})
\]
que satisfacen la condición de que para cada \(1 \leq k \leq n\) podemos derivar el juicio
\[ x_1: A_1, \ldots, x_{k-1}: A_{k-1}(x_1, \ldots, x_{k-2}) \vdash A_k (x_1, \ldots, x_{k-1} ~~~ \text{type})\]
usando las reglas de inferencia de la teoría de tipos. Podemos usar nombres de variables que no sean
\(x_1, \ldots, x_n\) siempre que no declaremos una misma variable más de una vez.

La condición de la Definición [[#definicion-1-1-2][1.1.2]] de que cada uno de los elementos hipotéticos tiene asignado un tipo,
es verificado recursivamente. En otras palabras, para verificar que una declaración de variables como
en la ecuación \eqref{eq:lista-contexto} es un contexto, uno empieza por la izquierda y se va
trabajando hacia la derecha, verificando que cada elemento hipotético \(x_k\) tenga un tipo asignado.

Notemos que hay un contexto de longitud 0, el *contexto vacío*, en el que no se declara ninguna variable.
Este contexto satisface la definición [[#definicion-1-1-2][1.1.2]] por vacuidad. Una lista de declaraciones de variables
\(x_1: A_1\) es un contexto si y sólo si \(A_1\) es un tipo en el contexto vacío.
* Familias de tipos
Una característica de la teoría de tipos dependiente es que todos los juicios dependen del contexto e
incluso los tipos de las variables en un contexto pueden depender de otras variables ya declaradas.
Por ejemplo, si \(n\) es un número natural y sabemos del contexto que \(n\) es primo, entonces no tenemos
suficiente información para afirmar que \(n\) es impar. Sin embargo, si sabemos del contexto que \(n + 2\)
es primo, entonces podemos derivar del contexto que \(n\) debe ser impar.

** Definición 1.2.1
Consideremos un tipo \(A\) en un contexto \(\Gamma\). Una *familia* de tipos sobre \(A\) en un contexto \(\Gamma\) es un tipo
\(B(x)\) en el contexto \(\Gamma, x: A\). En otras palabras, en la situación en la que
\[ \Gamma, x: A \vdash B(x) ~~~ \text{type} \],
decimos que \(B\) es una familia de tipos sobre \(A\) en el contexto \(\Gamma\). Alternativamente, decimos que
\(B(x)\) es un tipo *indizado* por \(x: A\), en el contexto \(\Gamma\).

Pensamos en una familia de tipos \(B\) sobre \(A\) en un contexto \(\Gamma\) como un tipo \(B(x)\) que varía a lo largo
de \(x: A\). Un ejemplo básico de una familia de tipos ocurre cuando introducimos los *tipos identidad*.
Se introducen como sigue:
\[
        \frac{\Gamma \vdash a: A}{\Gamma, x: A \vdash a = x ~~~ \text{type}}
\]
Esta regla afirma que dado un elemento \(a: A\) en el contexto \(\Gamma\), podemos formar el tipo \(a = x\) en el
contexto \(\Gamma, x: A\). El tipo \(a = x\) en el contexto \(\Gamma, x: A\) es un ejemplo de familia de tipos sobre \(A\)
en un contexto \(\Gamma\).

** Definición 1.2.2
Consideremos una familia de tipos \(B\) sobre \(A\) en un contexto \(\Gamma\). Una *sección* de la familia \(B\) sobre \(A\)
en el contexto \(\Gamma\) es un elemento de tipo \(B(x)\) en el contexto \(\Gamma, x: A\), i.e., en el juicio
\[
        \Gamma, x: A \vdash b(x): B(x)
\]
decimos que \(b\) es una sección de la familia \(B\) sobre \(A\) en el contexto \(\Gamma\). Alternativamente, decimos que
\(b(x)\) es un elemento de tipo \(B(x)\) indizado por \(x: A\) en el contexto \(\Gamma\).
* Reglas de inferencia
Ahora estamos listos para presentar el sistema de reglas de inferencia que subyace a la teoría de tipos
dependiente. Estas son conocidas como *reglas estructurales* de la teoría de tipos, pues establecen la
estructura matemática para la dependencia de tipos. Hay seis conjuntos de reglas de inferencia:
1. Reglas sobre la formación de contextos, tipos y sus elementos.
2. Reglas que postulan que la igualdad juiciosa es una relación de equivalencia.
3. Reglas de conversión de variables.
4. Reglas de substitución.
5. Reglas de debilitamiento.
6. El elemento genérico.

** Reglas sobre la formación de contextos, tipos y sus elementos
En la definición de contextos, tipos y elementos bien formados, especificamos que para que un tipo
\(B(x)\) esté bien formado en un contexto \(\Gamma, x: A\), debe suceder que \(A\) sea un tipo bien formado en el
contexto \(\Gamma\). Las siguientes reglas se siguen de las suposiciones sobre contextos, tipos y sus elementos
y se pueden usar libremente en las derivaciones:
\begin{array}{ccc}
        \dfrac{\Gamma, x: A \vdash B(x) ~~~ \text{type}}{\Gamma \vdash A ~~~ \text{type}} &
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} B ~~~ \text{type}}{\Gamma \vdash A ~~~ \text{type}} &
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} B ~~~ \text{type}}{\Gamma \vdash B ~~~ \text{type}} \\
        \dfrac{\Gamma \vdash a: A}{\Gamma \vdash A ~~~ {type}} &
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} b: A}{\Gamma \vdash a: A} &
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} b}{\Gamma \vdash b: A}
\end{array}

** La igualdad juiciosa es una relación de equivalencia
Las reglas que postulan que la igualdad sobre tipos y sus elementos es una relación de equivalencia
simplemente postulan que es reflexiva, simétrica y transitiva:
\begin{array}{ccc}
        \dfrac{\Gamma \vdash A ~~~ \text{type}}{\Gamma \vdash A \stackrel{\cdot}{=} A ~~~ \text{type}} &
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} B ~~~ \text{type}}{\Gamma \vdash B \stackrel{\cdot}{=} A ~~~ ~\text{type}} &
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} B ~~~ \text{type} ~~~ \Gamma \vdash B \stackrel{\cdot}{=} C ~~~ \text{type}}{\Gamma \vdash A \stackrel{\cdot}{=} C ~~~ \text{type}} \\
        \dfrac{\Gamma \vdash a: A}{\Gamma \vdash a \stackrel{\cdot}{=} a: A} &
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} b: A}{\Gamma \vdash b \stackrel{\cdot}{=} a: A} &
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} b: A ~~~ \Gamma \vdash b \stackrel{\cdot}{=} c: A}{\Gamma \vdash a \stackrel{\cdot}{=} c: A}
\end{array}

** Reglas de conversión de variables
Las *reglas de conversión de variables* postulan que podemos convertir el tipo de una variable
a un tipo juiciosamente igual. La primera regla de conversión de variables dice que

\[
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} A' ~~~ \text{type} ~~~ \Gamma, x: A, \Delta \vdash B(x) ~~~ \text{type}}{\Gamma, x: A', \Delta \vdash B(x) ~~~ \text{type}}.
\]

En esta regla de conversión, el contexto \(\Gamma, x: A, \Delta\) es simplemente cualquier extensión del contexto
\(\Gamma, x: A\).
Similarmente, hay reglas de conversión para igualdad juiciosa de tipos, elementos y para la igualdad
juiciosa de elementos. Escribimos una única regla para estas con una *tesis de juicio genérico*
\(\mathcal{J}\), que puede ser cualquiera de las definidas en la definición [[#definicion-1-1-1][1.1.1]]:

\[
        \dfrac{\Gamma \vdash A \stackrel{\cdot}{=} A' ~~~ \text{type} ~~~ \Gamma, x: A, \Delta \vdash \mathcal{J}}{\Gamma, x: A', \Delta \vdash \mathcal{J}}.
\]
** Substitución
Consideremos un elemento \(f(x): B(x)\) indizado por \(x: A\) en el contexto \(\Gamma\), y supongamos que tenemos un
elemento \(a: A\). Entonces podemos substituir \(a\) por todas las ocurrencias de \(x\) en \(f(x)\) para obtener un
nuevo elemento \(f[a/x]\), que tiene tipo \(B[a/x]\).
Supongamos que tenemos un tipo

\[
        \Gamma, x: A, y_1: B_1, \ldots, y_n: B_n \vdash C ~~~ \text{type}
\]

y un elemento \(a: A\) en el contexto \(\Gamma\). Entonces podemos substituir simultáneamente \(a\) por todas las
ocurrencias de \(x\) en los tipos \(B_1, \ldots, B_n\) y \(C\) para obtener

\[
        \Gamma, y_1: B_1[a/x], \ldots, y_n: B_n[a/x] \vdash C[a/x] ~~~ \text{type}.
\]

Notemos que a las variables \(y_1, \ldots, y_n\) se les asignan nuevos tipos después de realizar la substitución
de \(a\) por \(x\). Similarmente, podemos substituir \(a\) por \(x\) en un elemento \(c: C\) para obtener un elemento
\(c[a/x]: C[a/x]\), y podemos substituir \(a\) por \(x\) en una tesis de igualdad juiciosa ya sea de tipos o
elementos, simplemente substituyendo en ambos lados de la ecuación. La *regla de substitución* es enunciada
usando una tesis de juicio genérico \(\mathcal{J}\):

\[
        \dfrac{\Gamma \vdash a: A ~~~ \Gamma, x: A, \Delta \vdash \mathcal{J}}{\Gamma, \Delta[a/x] \vdash \mathcal{J}[a/x]}S.
\]

Más aún, añadimos dos "reglas de congruencia" para la substitución, que postulan que la substitución
por elementos juiciosamente iguales resulta en tipos y elementos juiciosamente iguales:

\begin{array}{c}
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} a': A ~~~ \Gamma, x: A, \Delta \vdash B ~~~ \text{type}}{\Gamma, \Delta[a/x] \vdash B[a/x] \stackrel{\cdot}{=} B[a'/x] ~~~ \text{type} } \\
        \dfrac{\Gamma \vdash a \stackrel{\cdot}{=} a': A ~~~ \Gamma, x: A, \Delta \vdash b: B}{\Gamma, \Delta[a/x] \vdash b[a/x] \stackrel{\cdot}{=} b[a'/x]: B[a/x]
\end{array}

*** Definición 1.3.1
Cuando \(B\) es una familia de tipos sobre \(A\) en un contexto \(\Gamma\) y si tenemos \(a: A\), entonces también decimos
que \(B[a/x]\) es la *fibra* de \(B\) en \(a\). Usualmente escribimos \(B(a)\) para la fibra de \(B\) en \(a\).

Cuando \(b\) es una sección de la familia \(B\) sobre \(A\) en el contexto \(\Gamma\), llamamos al elemento \(b[a/x]\)
el *valor* de \(b\) en \(a\). Escribimos \(b(a)\) para el valor de \(b\) en \(a\).

** Debilitamiento
Si se nos da un tipo \(A\) en un contexto \(\Gamma\), entonces cualquier juicio hecho en un contexto más grande
\(\Gamma, \Delta\) también se puede hacer en el contexto \(\Gamma, x: A, \Delta\), para una variable fresca \(x\).
La regla de *debilitamiento* nos dice que el debilitamiento por un tipo \(A\) en un contexto \(\Gamma\) preserva
la buena formación y la igualdad juiciosa de tipos y elementos

\[
        \dfrac{\Gamma \vdash A ~~~ \text{type} ~~~ ~~~ \Gamma, \Delta \vdash \mathcal{J}}{\Gamma, x: A, \Delta \vdash \mathcal{J}}W.
\]

Este proceso de expandir el contexto por una nueva variable de tipo \(A\) es llamado *debilitamiento* por \(A\).

En la situación más simple en la que el debilitamiento aplica, tenemos dos tipos \(A\) y \(B\) en un contexto
\(\Gamma\). Entonces podemos debilitar \(B\) por \(A\) como sigue:

\[
        \dfrac{\Gamma \vdash A ~~~ \text{type} ~~~ ~~~ \Gamma \vdash B ~~~ \text{type}}{\Gamma, x: A \vdash B ~~~ \text{type}}
\]

para formar el tipo \(B\) en el contexto \(\Gamma, x: A\). El tipo \(B\) en el contexto \(\Gamma, x: A\) es llamado
la *familia constante* \(B\), o la *familia trivial* \(B\).


** Los elementos genéricos
Si se nos da un tipo \(A\) en un contexto \(\Gamma\), entonces podemos debilitar a \(A\) por si mismo para
obtener que \(A\) es un tipo en el contexto \(\Gamma, x: A\). La regla pala el *elemento genérico* asegura que
cualquier elemento hipotético \(x: A\) en el contexto \(\Gamma, x: A\) también es un elemento de tipo \(A\)
en el contexto \(\Gamma, x: A\).

\[
        \dfrac{\Gamma \vdash A ~~~ \text{type}}{\Gamma, x: A \vdash x: A} \delta.
\]

Esta regla también es conocida como *regla de variable*. Una de las razones para incluir el elemento
genérico es asegurarnos de que las variables declaradas en un contexto son de hecho elementos. También
da la *función identidad* sobre el tipo \(A\) en el contexto \(\Gamma\).


* Derivaciones
Una *derivación* en la teoría de tipos es un árbol finito en el que cada nodo es una regla de inferencia
válida. En la raíz del árbol encontramos la conclusión y en las hojas encontramos las hipótesis. Damos
dos ejemplos de derivaciones: una derivación mostrando que cualquier variable se puede cambiar por una
variable nueva y una mostrando que dos variables que no dependen mutuamente de otra pueden ser cambiadas
en su orden.

Dada una derivación con hipótesis \(mathcal{H}_1, \ldots, \mathcal{H}_n\) y conclusión \(\mathcal{C}\),
podemos formar una nueva regla de inferencia

\[
        \dfrac{\mathcal{H}_1 \cdots \mathcal{H}_n}{\mathcal{C}}
\]

Una regla así es llamada *derivable*, pues podemos dar una derivación para ella.

*** Cambiando variables
Las variables se pueden cambiar por variables nuevas. Mostramos esto viendo que la regla de inferencia

\[
        \dfrac{\Gamma, x: A, \Delta \vdash \mathcal{J}}{\Gamma, x': A, \Delta[x'/x] \vdash \mathcal{J}[x'/x]}x'/x
\]

es derivable, donde \(x'\) es una variable que no ocurre en el contexto \(\Gamma, x: A, \Delta\).

En efecto, tenemos la siguiente derivación usando substitución, debilitamiento y el elemento genérico:

\[
        \dfrac{
                \dfrac{\Gamma \vdash A ~~~ \text{type}}{\Gamma, x': A \vdash x': A}\delta ~~~
                \dfrac{\Gamma \vdash A ~~~ \text{type} ~~~ ~~~ \Gamma, x: A, \Delta \vdash \mathcal{J}}{\Gamma, x': A, x: A, \Delta \vdash \mathcal{J}}W
        }{\Gamma, x': A, \Delta[x'/x] \vdash J[x'/x]}S.
\]

En esta derivación es en la regla de debilitamiento que debemos verificar que \(x'\) no ocurre en el
contexto \(\Gamma, x: A, \Delta\).

*** Intercambiando variables
La *regla de intercambio* dice que si tenemos dos tipos \(A\) y \(B\) en un contexto \(\Gamma\), y hacemos un
juicio en el contexto \(\Gamma, x: A, y: B, \Delta\), entonces podemos hacer el mismo juicio en el contexto
\(\Gamma, y: B, x: A, \Delta\) donde el orden de \(x: A\) y \(y: B\) es intercambiado. Más formalmente, la regla
de intercambio es la siguiente regla de inferencia
\[
        \dfrac{\Gamma \vdash B ~~~ \text{type} ~~~ ~~~ \Gamma, x: A, y:B, \Delta \vdash \mathcal{J}}{\Gamma, y: B, x: A, \Delta \vdash \mathcal{J}}.
\]

Como en la regla de cambio de variables, afirmamos que la regla de intercambio es derivable: si tenemos
un juicio
\[
        \Gamma, x: A, y: B, \Delta \vdash \mathcal{J},
\]
entonces podemos cambiar la variable \(y\) por una nueva variable \(y'\) y debilitar el juicio para
obtener el juicio
\[
\Gamma, y: B, x: A, y': B, \Delta[y'/y] \vdash \mathcal{J}[y'/y].
\]
Ahora podemos substituir \(y\) por \(y'\) para obtener el juicio deseado
\(\Gamma, y: B, x: A, \Delta \vdash \mathcal{J}\). La derivación formal es la siguiente:

\[
        \dfrac{
                \dfrac{
                        \dfrac{\Gamma \vdash B ~~~ \text{type}}{\Gamma, y: B \vdash y: B}
                }{\Gamma, y: B, x: A \vdash y: B}
                \dfrac{
                        \Gamma \vdash B ~~~ \text{type} ~~~ ~~~
                        \dfrac{
                                \Gamma, x: A, y: B, \Delta \vdash \mathcal{J}
                        }{\Gamma, x: A, y': B, \Delta[y'/y] \vdash \mathcal{J}[y'/y]}
                }{\Gamma, y: B, x: A, y': B, \Delta[y'/y] \vdash \mathcal{J}[y'/y]}
        }{\Gamma, y:B, x: A, \Delta \vdash \mathcal{J}}
\]
